/* Resource Heaps: browser controls and the resource-column view. */
(() => {
'use strict';
const M=window.ResourceHeap,$=id=>document.getElementById(id),clone=value=>JSON.parse(JSON.stringify(value));
const colours={a:'#70b6d3',b:'#a8c96d',c:'#e7bd61',d:'#e88972',e:'#bda4dc',f:'#eeaa55'};
const titles={climbers:'Climbers',builders:'Builders',porters:'Porters'};
const short={climbers:'C',builders:'B',porters:'P'};
let tasks=clone(M.DEFAULT_TASKS),caps=clone(M.DEFAULT_CAPACITIES),priority=tasks.map(t=>t.id),selected='c',current=null,exact=null,timer=null,shown=Infinity;
let activePreset='compact';
const notes={compact:'Two climbers, three builders, three porters. Try moving the cache to the front of the queue.',cache:'Same crew and work; the emergency cache gets first choice after the haul. Does that delay the shelter?',builder:'One more builder. Can the climbers keep up with the extra parallel work?',climber:'One more climber. Can the builders use the extra freedom?',both:'An extra climber and builder together. Compare the result with adding either one alone.'};
function element(tag,attrs={},text=''){const e=document.createElement(tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text)e.textContent=text;return e;}
function taskName(id){return tasks.find(t=>t.id===id)?.name||id;}
function resourcesText(t){return M.RESOURCE_TYPES.filter(r=>t.resources[r]).map(r=>`${t.resources[r]} ${titles[r].toLowerCase().replace(/s$/,t.resources[r]===1?'':'s')}`).join(' · ');}
function readLink(){const q=new URLSearchParams(location.search);if(!q.has('crew')&&!q.has('days')&&!q.has('order'))return;try{
 if(q.has('crew')){const v=q.get('crew').split(',').map(Number);if(v.length!==3)throw Error();caps=Object.fromEntries(M.RESOURCE_TYPES.map((r,i)=>[r,v[i]]));}
 if(q.has('days')){const v=q.get('days').split(',').map(Number);if(v.length!==tasks.length)throw Error();tasks.forEach((t,i)=>t.duration=v[i]);}
 if(q.has('order'))priority=q.get('order').split('');
 if(M.RESOURCE_TYPES.some(r=>!Number.isInteger(caps[r])||caps[r]<0||caps[r]>5)||tasks.some(t=>!Number.isInteger(t.duration)||t.duration<1||t.duration>5)||priority.length!==6||new Set(priority).size!==6||priority.some(id=>!tasks.some(t=>t.id===id)))throw Error();
 activePreset='';
 }catch(error){tasks=clone(M.DEFAULT_TASKS);caps=clone(M.DEFAULT_CAPACITIES);priority=tasks.map(t=>t.id);$('save-status').textContent='That scenario link contained unsupported inputs. The original example is shown.';}}
function scenarioURL(){const u=new URL(location.href);u.searchParams.set('crew',M.RESOURCE_TYPES.map(r=>caps[r]).join(','));u.searchParams.set('days',tasks.map(t=>t.duration).join(','));u.searchParams.set('order',priority.join(''));return u.href;}
function syncURL(){try{history.replaceState(null,'',scenarioURL());}catch(error){/* Local file views still support explicit copied links. */}}
function buildInputs(){const crew=$('capacity-inputs');crew.replaceChildren();for(const r of M.RESOURCE_TYPES){const wrap=element('div',{class:'crew-field'}),label=element('label',{for:`crew-${r}`},titles[r]),input=element('input',{id:`crew-${r}`,type:'number',min:'0',max:'5',step:'1','aria-label':`${titles[r]} available`});input.value=caps[r];input.addEventListener('input',()=>{caps[r]=input.value===''?NaN:Number(input.value);activePreset='';recompute();});wrap.append(label,input);crew.append(wrap);}
 const body=$('task-table');body.replaceChildren();for(const t of tasks){const row=element('tr'),name=element('td'),badge=element('span',{class:'task-token'},t.id.toUpperCase());badge.style.background=colours[t.id];name.append(badge,document.createTextNode(t.name));const duration=element('td'),input=element('input',{type:'number',min:'1',max:'5',step:'1','aria-label':`Days for ${t.name}`});input.value=t.duration;input.addEventListener('input',()=>{t.duration=input.value===''?NaN:Number(input.value);activePreset='';recompute();});duration.append(input);row.append(name,duration,element('td',{},resourcesText(t)),element('td',{},t.predecessors.length?t.predecessors.map(taskName).join(', '):'None'));body.append(row);}}
function drawPriority(focus){const list=$('priority-list');list.replaceChildren();priority.forEach((id,index)=>{const li=element('li'),badge=element('span',{class:'task-token'},id.toUpperCase());badge.style.background=colours[id];li.append(badge,element('span',{class:'priority-name'},taskName(id)));for(const[delta,arrow,label]of[[-1,'↑','Raise'],[1,'↓','Lower']]){const button=element('button',{'aria-label':`${label} priority of ${taskName(id)}`,'data-priority':`${id}:${delta}`},arrow);button.disabled=index+delta<0||index+delta>=priority.length;button.addEventListener('click',()=>{[priority[index],priority[index+delta]]=[priority[index+delta],priority[index]];activePreset='';recompute(`${id}:${delta}`);});li.append(button);}list.append(li);});if(focus){const e=list.querySelector(`[data-priority="${focus}"]`);if(e&&!e.disabled)e.focus();}}
function stopAnimation(){clearInterval(timer);timer=null;shown=Infinity;$('animate').textContent='Build the view';}
function svgEl(tag,attrs={},text=''){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text)e.textContent=text;return e;}
function drawHeap(){const target=$('heap');target.replaceChildren();if(!current?.ok){target.append(element('p',{class:'empty-heap'},'No valid pile for these inputs. Adjust the crew or durations above.'));return;}
 const cell=42,gap=24,left=54,top=50,bottom=42,day=30,span=current.makespan,height=top+bottom+span*day;let width=left+12,positions={};for(const r of M.RESOURCE_TYPES){positions[r]=width;width+=caps[r]*cell+gap;}width-=gap-12;const svg=svgEl('svg',{viewBox:`0 0 ${width} ${height}`,role:'group','aria-label':`Verified resource-column schedule, ${span} days. Individual task blocks are selectable.`});
 svg.append(svgEl('title',{},'A resource heap for the selected schedule'));for(let t=0;t<=span;t++){const y=height-bottom-t*day;svg.append(svgEl('line',{x1:left-4,x2:width-10,y1:y,y2:y,stroke:t===0?'#a5bda8':'#2d453c','stroke-width':t===0?2:1}));svg.append(svgEl('text',{x:left-12,y:y+4,'text-anchor':'end',fill:'#abc0b3','font-size':10},String(t)));}svg.append(svgEl('text',{x:12,y:top+span*day/2,fill:'#abc0b3','font-size':10,transform:`rotate(-90 12 ${top+span*day/2})`},'Elapsed days ↑'));
 for(const r of M.RESOURCE_TYPES){const x=positions[r],n=caps[r];svg.append(svgEl('text',{x:x+n*cell/2,y:18,'text-anchor':'middle',fill:'#e6efe7','font-size':12,'font-weight':600},titles[r]));for(let i=0;i<n;i++){svg.append(svgEl('rect',{x:x+i*cell,y:top,width:cell,height:span*day,fill:'transparent',stroke:'#2d453c'}));svg.append(svgEl('text',{x:x+(i+.5)*cell,y:height-bottom+20,'text-anchor':'middle',fill:'#abc0b3','font-size':10},short[r]+(i+1)));}}
 const ordered=[...current.schedule].sort((a,b)=>a.start-b.start||a.id.localeCompare(b.id));ordered.forEach((entry,i)=>{const group=svgEl('g',{class:'task-piece',role:'button',tabindex:i<shown?0:-1,'aria-hidden':String(i>=shown),'aria-label':`${taskName(entry.id)}, starts ${entry.start}, finishes ${entry.end} days`,'data-task':entry.id,opacity:i<shown?(selected===entry.id?1:.68):0});group.addEventListener('click',()=>selectTask(entry.id));group.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectTask(entry.id);}});group.append(svgEl('title',{},`${taskName(entry.id)} · ${entry.start}–${entry.end} days`));for(const r of M.RESOURCE_TYPES)for(const unit of(entry.units[r]||[])){const x=positions[r]+unit*cell+2,y=height-bottom-entry.end*day+2,h=(entry.end-entry.start)*day-4;group.append(svgEl('rect',{x,y,width:cell-4,height:h,rx:4,fill:colours[entry.id],stroke:selected===entry.id?'#fffef0':'#0e221b','stroke-width':selected===entry.id?2:1}));group.append(svgEl('text',{x:x+(cell-4)/2,y:y+h/2+4,'text-anchor':'middle',fill:'#142d25','font-size':12,'font-weight':700,'pointer-events':'none'},entry.id.toUpperCase()));}svg.append(group);});target.append(svg);
}
function drawLegend(){const l=$('legend');l.replaceChildren();for(const t of tasks){const b=element('button',{'aria-pressed':String(selected===t.id)}),badge=element('span',{class:'task-token'},t.id.toUpperCase());badge.style.background=colours[t.id];b.append(badge,document.createTextNode(t.name));b.addEventListener('click',()=>selectTask(t.id));l.append(b);}}
function inspect(){const t=tasks.find(t=>t.id===selected),entry=current?.schedule?.find(s=>s.id===selected);$('inspection-title').textContent=t.name;const panel=$('inspection-details');panel.replaceChildren();if(!entry){$('inspection-copy').textContent='This task cannot be placed under the current inputs.';return;}
 $('inspection-copy').textContent=t.id==='f'?'The cache is fitted in its own prepared recess. It needs the haul to finish, then competes for climbers and porters.':(t.predecessors.length?`The physical rule waits for ${t.predecessors.map(taskName).join(' and ')} to finish.`:'The haul has no predecessor in this model.');const facts=[['Start → finish',`${entry.start} → ${entry.end} days`],['Duration',`${t.duration} days`],['Prerequisites ready',`${entry.predecessorReady} days`],['Wait for resources',`${entry.resourceDelay} days`],['Assigned units',M.RESOURCE_TYPES.flatMap(r=>(entry.units[r]||[]).map(i=>short[r]+(i+1))).join(', ')]];for(const[label,value]of facts)panel.append(element('dt',{},label),element('dd',{},value));}
function selectTask(id){selected=id;drawHeap();drawLegend();inspect();}
function recompute(focus){$('export-panel').hidden=true;$('export-json').value='';stopAnimation();drawPriority(focus);document.querySelectorAll('[data-preset]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.preset===activePreset)));$('scenario-note').textContent=notes[activePreset]||'Custom inputs. Every change is recalculated against the same declared project rules.';
 current=M.schedulePriority(tasks,caps,priority);exact=M.solveExact(tasks,caps);const v=current.ok?M.verifySchedule(tasks,caps,current.schedule):{ok:false};if(current.ok&&!v.ok)current={ok:false,errors:['The schedule did not pass verification.'],schedule:[]};const ok=current.ok&&exact.ok&&v.ok;for(const id of['use-best','animate','download','alternatives'])$(id).disabled=!ok;
 $('problem').hidden=ok;$('problem').textContent=ok?'':(current.errors||exact.errors||['No feasible schedule.']).join(' ');
 $('current-finish').textContent=ok?`${current.makespan} days`:'—';$('best-finish').textContent=ok?`${exact.bestMakespan} days`:'—';$('gap').textContent=ok?`${current.makespan-exact.bestMakespan} days`:'—';$('verified').textContent=v.ok?'Replay passed':'No valid schedule';$('priority-note').textContent=ok?`Actual placement order: ${current.order.map(id=>id.toUpperCase()).join(' → ')}.`:'No tasks placed.';
 $('search-summary').textContent=ok?`All ${exact.ordersChecked} prerequisite-respecting priority orders were checked, giving ${exact.uniqueSchedules} distinct earliest-start schedule${exact.uniqueSchedules===1?'':'s'}. ${exact.optimalCount} ${exact.optimalCount===1?'finishes':'finish'} in ${exact.bestMakespan} days. Your schedule passes task coverage, timing, prerequisites, team capacity and individual-unit checks.`:'No optimisation claim is made for invalid or impossible inputs.';
 $('bounds').textContent=ok?`Lower bounds: ${exact.criticalPathBound} days from the longest prerequisite chain; ${exact.resourceWorkBound} days from total work divided by crew capacity. The complete priority search establishes the displayed best finish.`:'';
 const select=$('alternatives');select.replaceChildren();if(ok)exact.schedules.forEach((s,i)=>{const o=element('option',{value:i},`${s.makespan} days · ${s.order.map(x=>x.toUpperCase()).join(' → ')}`);if(s.schedule.every(e=>current.schedule.some(c=>c.id===e.id&&c.start===e.start)))o.selected=true;select.append(o);});
 $('animation-note').textContent=ok?'All blocks shown. “Build the view” reveals scheduled tasks in start-time order; it does not simulate construction.':'';drawHeap();drawLegend();inspect();const shareable=M.RESOURCE_TYPES.every(r=>Number.isInteger(caps[r])&&caps[r]>=0&&caps[r]<=5)&&tasks.every(t=>Number.isInteger(t.duration)&&t.duration>=1&&t.duration<=5);$('copy-link').disabled=!shareable;if(shareable)syncURL();}
$('use-best').addEventListener('click',()=>{if(exact?.ok){priority=[...exact.best.order];activePreset='';recompute();}});
$('alternatives').addEventListener('change',e=>{const s=exact.schedules[Number(e.target.value)];if(s){priority=[...s.order];activePreset='';recompute();}});
$('animate').addEventListener('click',()=>{if(timer){stopAnimation();drawHeap();$('animation-note').textContent='All blocks shown.';return;}if(!current?.ok)return;shown=0;$('animation-note').textContent='0 of 6 task bundles revealed.';$('animate').textContent='Show all blocks';drawHeap();timer=setInterval(()=>{shown++;drawHeap();$('animation-note').textContent=`${Math.min(shown,tasks.length)} of ${tasks.length} task bundles revealed.`;if(shown>=tasks.length){stopAnimation();drawHeap();}},window.matchMedia('(prefers-reduced-motion: reduce)').matches?1:550);});
function preset(name){tasks=clone(M.DEFAULT_TASKS);caps=clone(M.DEFAULT_CAPACITIES);priority=tasks.map(t=>t.id);if(name==='cache')priority=['a','f','b','c','d','e'];if(name==='builder'||name==='both')caps.builders=4;if(name==='climber'||name==='both')caps.climbers=3;activePreset=name;selected=name==='cache'?'f':'c';buildInputs();recompute();}
for(const b of document.querySelectorAll('[data-preset]'))b.addEventListener('click',()=>preset(b.dataset.preset));
$('reset').addEventListener('click',()=>{preset('compact');$('save-status').textContent='Original crew, durations and priority restored.';$('scenario-link').hidden=true;$('link-label').hidden=true;});
$('copy-link').addEventListener('click',async()=>{const url=scenarioURL();$('scenario-link').value=url;$('scenario-link').hidden=false;$('link-label').hidden=false;try{await navigator.clipboard.writeText(url);$('save-status').textContent='Scenario link copied. It restores your inputs and priority when reopened.';}catch(error){$('scenario-link').focus();$('scenario-link').select();$('save-status').textContent='Your scenario link is selected below; copy it to keep this result.';}});
$('download').addEventListener('click',()=>{if(!current?.ok||!exact?.ok)return;const receipt={schema:'gimmer-resource-heaps-v1',createdAt:new Date().toISOString(),scenarioURL:scenarioURL(),method:'Single-mode RCPSP; exhaustive precedence-feasible priority orders with serial schedule generation',source:'https://arxiv.org/html/1708.07786',assumptions:'Fictional fixed tasks; uninterrupted integer durations; renewable interchangeable teams; finish-to-start prerequisites; emergency cache at a separate prepared recess; all tasks required.',tasks:clone(tasks),capacities:clone(caps),priority:[...priority],schedule:clone(current.schedule),makespan:current.makespan,bestMakespan:exact.bestMakespan,ordersChecked:exact.ordersChecked,uniqueEarliestSchedules:exact.uniqueSchedules,verification:M.verifySchedule(tasks,caps,current.schedule)};const json=JSON.stringify(receipt,null,2)+'\n';$('export-json').value=json;$('export-panel').hidden=false;const blob=new Blob([json],{type:'application/json'}),url=URL.createObjectURL(blob),a=element('a',{href:url,download:'gimmer-resource-heap.json'});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('save-status').textContent='Schedule JSON prepared below and download requested: gimmer-resource-heap.json. If no file appears, use Copy this JSON.';});
$('copy-json').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('export-json').value);$('save-status').textContent='Prepared schedule JSON copied. Paste it into a text file to keep or inspect this result.';}catch(error){$('export-json').focus();$('export-json').select();$('save-status').textContent='Prepared JSON selected below. Copy it to keep this result.';}});
readLink();buildInputs();recompute();
})();
